name: Build and Test
on:
  - push

jobs:
  linux64:
    name: Build and Test (Linux x64)
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Download dependencies and build
        run: GOOS=linux GOARCH=amd64 go build -i -o rsteamstatus
      
      - name: Run tests
        run: go test
        env:
          R_STATUS_URL: ${{ secrets.R_STATUS_URL }}
          R_CLIENT_ID: ${{ secrets.R_CLIENT_ID }}
          R_CLIENT_SECRET: ${{ secrets.R_CLIENT_SECRET }}
          R_USERNAME: ${{ secrets.R_USERNAME }}
          R_PASSWORD: ${{ secrets.R_PASSWORD }}
          R_USER_AGENT: rsteamstatus/1.1 (CI tests; /u/antigravities; developers@cutie.cafe)
          R_SUBREDDIT: uniQTestArea

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: rsteamstatus-linux-x64
          path: rsteamstatus
